### ISSUE TITLE
Module not found: Can't resolve '.postshey.mdx'

### ISSUE THREAD

**Issue by i-am-henri** [souporserious/mdxts#121] opened 2024-05-15 15:48 UTC
Hey, I'm getting this error when I try to set mdxts up:

![image](https://github.com/souporserious/mdxts/assets/98414850/048657c0-0362-4ef7-9e85-7c207d23a561)
I think it searches for a file with this name: '.postshey.mdx', and can't read the folders.
I've set up all correctly, my data.ts and my folder structure:
![image](https://github.com/souporserious/mdxts/assets/98414850/ea5f034f-cf25-449f-ba02-122d2f932fcb)
![image](https://github.com/souporserious/mdxts/assets/98414850/dd8607ae-3900-4ae4-9ade-16c5722ca304)

I'm using the latest nextjs version, with this package.json:
![image](https://github.com/souporserious/mdxts/assets/98414850/b2a5d29e-436a-42f0-88f7-985bc62e29d0)

**Comment by i-am-henri** [comment] 2024-05-15 15:54
One another problem: The CLI is on my machine not working (windows):
![image](https://github.com/souporserious/mdxts/assets/98414850/b41a8db3-7533-4690-992c-93a105cb0170)

**Comment by lanwin** [comment] 2024-05-16 07:03
Seems to be the same problem as this: https://github.com/souporserious/mdxts/issues/108

**Comment by souporserious** [comment] 2024-06-02 03:03
Closing as a duplicate of #108. I still need to set up Windows testing, but this may be fixed now with the recent path changes.

**Closed by souporserious** 2024-06-02 03:03 UTC
